### ISSUE TITLE
Accessing basic user information

### ISSUE THREAD

**Issue by nteetor** [Azure/AzureAuth#17] opened 2019-10-15 13:57 UTC
Hello again,

I am not sure whether to open an issue here or under the AzureGraph repo. I am struggling to understand how to access basic user information like their username or email as part of the auth token payload. The Azure AD documentation suggests their email or username can come back with the payload. I've tried adjusting my application's settings and api permissions and have never once seen any additional info come back. 

I thought perhaps I needed to use graph then. However, I first ran into this error when trying to use my auth token to call `create_graph_login()`,

```
Current authenticated context is not valid for this
request. This occurs when a request is made to an
endpoint that requires user sign-in. For example, /me
requires a signed-in user.  Acquire a token on behalf
of a user to make requests to these endpoints.  Use
the OAuth 2.0 authorization code flow for mobile and
native apps and the OAuth 2.0 implicit flow for
single-page web apps.
```

So, I followed the AzureAuth example for acquiring a token on behalf of another token. I noticed the example uses two distinct app IDs. I am working with a single application, one id. Here is the error I got back while trying to request a second token for graph on behalf of my initial auth token,

```
Assertion failed signature validation. [Reason - The provided signature value did not match the expected signature value., Thumbprint of key used by client: '<REDACTED ALPHA NUMERIC>', Found key 'Start=08/25/2019 00:00:00, End=08/24/2024 00:00:00']
```

My application does request the resource in the auth process, 

```
https://graph.microsoft.com/.default
```

And I think I have the correct permissions set,

<img width="529" alt="image" src="https://user-images.githubusercontent.com/3228369/66837796-97291a00-ef31-11e9-9758-d783d353962c.png">

Do you see any glaring issues in my worflow? Can I avoid using AzureGraph and still get username and email address (if set) with my initial auth token request? Thank you again.

**Comment by nteetor** [comment] 2019-10-15 15:43
I will work on getting the code into a format I can share. As I mentioned before, this is part of a shiny application and I'm not comfortable running the authentication piece without firing up the entire application. 

I can tell you now the payload I get back has never included `family_name` or `given_name`. The payload I get back includes the following fields, 

```
aud
iss
iat
nbf
exp
aio
app_displayname
appid
appidacr
idp
tid
uti
ver
xms_tcdt
```

**Comment by nteetor** [comment] 2019-10-15 16:12
I notice your response is a v1 Token. I have been using v2 oauth. Sorry, I realize this would evident if you had the code I am using. 

I can also say it looks like I am unable change the `response_type` of my auth request. So although `openid` is included in my requested scopes, I don't see `response_type=id_token` in the outgoing request. Could this be preventing openid authentication?

Here is the code I am using in the auth process. The second function gives me the error about provided signature values.

```R
azure_auth_user <- function(code) {
  if (is.null(code)) {
    return()
  }
  
  azure <- config::get("azure")
  
  with(azure, {
    AzureAuth::get_azure_token(
      resource = RESOURCE,
      tenant = TENANT, 
      app = APP,
      password = SECRET,
      # auth_type = "authorization_code",
      authorize_args = list(
        redirect_uri = REDIRECT,
        response_type = "id_token"
      ),
      auth_code = code,
      use_cache = FALSE,
      version = 2
    )
  })
}

azure_auth_graph <- function(user) {
  if (is.null(user)) {
    return()
  }
  
  azure <- config::get("azure")
  
  with(azure, {
    AzureAuth::get_azure_token(
      resource = "https://graph.microsoft.com",
      tenant = TENANT,
      app = APP,
      password = SECRET,
      on_behalf_of = user
    )
  })
}
```

**Comment by nteetor** [comment] 2019-10-15 16:15
This the config file I am using,

```
default:
  azure:
    RESOURCE: 
      - https://graph.microsoft.com/.default
      - openid
      - profile
      - email
      - offline_access
    TENANT: common
    APP: <redacted>
    REDIRECT: http://localhost:8080
    SECRET: <redacted>
```

**Comment by Hong-Revo** [comment] 2019-10-15 17:00
That code is exactly what is needed, thank you. The fact that you're using Shiny is just a distraction, it only means that you need to separate the authorization and token acquisition steps. This is why the `build_authorization_uri` function exists, so that the UI can get the authcode and the server can then use it to get the token.

When you do this:

```r
    AzureAuth::get_azure_token(
      resource = RESOURCE,
      tenant = TENANT, 
      app = APP,
      password = SECRET,
      # auth_type = "authorization_code",
      . . .
```

You are using the client_credentials auth flow, since you provided a password. This authenticates as the app, not as a user, which explains why you don't have any user info in the token. The fact that the UI didn't redirect you to the AAD login page should have been a clue, although this might have been skipped if you're using the cache.

To login as the user, put this in your UI:

```r
code <- build_authorization_uri(resource, tenant, app,
    redirect_uri="<redirect>",
    version=2)
```

And put this in your server:

```r
get_azure_token(resource, tenant, app,
    password=password,
    auth_type="authorization_code",
    version=2,
    auth_code=code,
    authorize_args=list(redirect_uri="<redirect>"))
```

**Comment by nteetor** [comment] 2019-10-15 17:32
The application does redirect. Below is the function I use to generate the URI. This is based on the shiny vignette included with the package,

```R
azure_auth_uri <- function(code) {
  if (!is.null(code)) {
    return()
  }
  
  azure <- config::get("azure")
  
  with(azure, {
    AzureAuth::build_authorization_uri(
      resource = RESOURCE,
      tenant = TENANT, 
      app = APP, 
      redirect_uri = REDIRECT,
      version = 2
    )
  })
}
```

If I do not include `password` in `get_azure_token()` I run into errors about not including a client_secret. The idea I am authenticating as the wrong person does sound accurate though. I spoke earlier with a coworker who worked through the Node examples. As we discussed I noticed my requests were hitting different endpoints. Although we both thought were using openid auth.

**Comment by nteetor** [comment] 2019-10-15 17:44
I am little surprised to find that certain values are ignored by the `authorize_args` argument. I tried to specify both `response_type` and `client_secret`, but neither appear in the outgoing auth request.

**Comment by Hong-Revo** [comment] 2019-10-15 17:52
Again, PLEASE PROVIDE THE CODE YOU RUN IN YOUR SHINY APP. This is both on the UI and server side.

**Comment by nteetor** [comment] 2019-10-15 18:01
I'm glad our relationship has reached the capslock phase 😁 . I'll be right back with some code snippets. WARNING: there won't be much more than what is shown above.

**Comment by Hong-Revo** [comment] 2019-10-15 18:03
You need to show what you have in your server, not just what's in your UI. In particular, don't comment out the `auth_type` argument to `get_azure_token`.

**Comment by nteetor** [comment] 2019-10-15 18:14
Here is the updated `azure_auth_user()` function from above, the [config file](https://github.com/Azure/AzureAuth/issues/17#issuecomment-542292116) has not changed,

```R
azure_auth_user <- function(code) {
  if (is.null(code)) {
    return()
  }
  
  azure <- config::get("azure")
  
  with(azure, {
    AzureAuth::get_azure_token(
      resource = RESOURCE,
      tenant = TENANT, 
      app = APP,
      # password = SECRET,               # <- now commented
      auth_type = "authorization_code",  # <- now uncommented
      authorize_args = list(
        redirect_uri = REDIRECT,
        response_type = "id_token code",  # <- not present in request
        client_secret = SECRET            # <- not present in request
      ),
      auth_code = code,
      use_cache = FALSE,
      version = 2
     )
  })
}
```

Some good news (I think), the redirect re-requested my login, so something under-the-hood definitely changed. However, I still ran into the client_secret error. 

Here is the request that went out when calling `azure_auth_user()`,

```
-> POST /common/oauth2/v2.0/token HTTP/1.1
-> Host: login.microsoftonline.com
-> User-Agent: libcurl/7.54.0 r-curl/4.1 httr/1.4.0
-> Accept-Encoding: deflate, gzip
-> Accept: application/json, text/xml, application/xml, */*
-> Content-Type: application/x-www-form-urlencoded
-> Content-Length: 162
-> 
>> client_id=<REDACTED>&grant_type=authorization_code&code=M01ef30ee-69cd-7f51-08cd-73428643bd24&redirect_uri=http%3A%2F%2Flocalhost%3A8080
```

**Comment by Hong-Revo** [comment] 2019-10-15 18:32
Don't comment out `password` either. You have a webapp so you need to pass the client secret to the token endpoint.

**Comment by nteetor** [comment] 2019-10-15 18:33
(for the record, I am shocked and humbled by your assistance, I'm not certain what is the root of the issues I am dealing with, but without your assistance I would have gotten nowhere and there'd be some very unhappy clients)

**Comment by Hong-Revo** [comment] 2019-10-15 18:33
And don't put `client_secret` or `id_token` in `authorize_args`.

**Comment by nteetor** [comment] 2019-10-15 18:35
Regarding, `password` I misunderstood the [comment](https://github.com/Azure/AzureAuth/issues/17#issuecomment-542310300) from above. I will put back in `password`.

I can drop `id_token` and `client_secret`, too. 

I will have the updated code and response in a moment.

**Comment by nteetor** [comment] 2019-10-15 18:42
Here is the updated `azure_auth_user()` function (config unchanged),

```R
azure_auth_user <- function(code) {
  if (is.null(code)) {
    return()
  }
  
  azure <- config::get("azure")
  
  with(azure, {
    AzureAuth::get_azure_token(
      resource = RESOURCE,
      tenant = TENANT, 
      app = APP,
      password = SECRET,
      auth_type = "authorization_code",
      authorize_args = list(
        redirect_uri = REDIRECT
      ),
      auth_code = code,
      use_cache = FALSE,
      version = 2
    )
  })
}
```

Here is the request that went out,

```
-> POST /common/oauth2/v2.0/token HTTP/1.1
-> Host: login.microsoftonline.com
-> User-Agent: libcurl/7.54.0 r-curl/4.1 httr/1.4.0
-> Accept-Encoding: deflate, gzip
-> Cookie: fpc=AoW_O_xZa1JDtkEpmO1t5N2sfWnoAQAAAN4BONUOAAAA; stsservicecookie=ests; x-ms-gateway-slice=prod
-> Accept: application/json, text/xml, application/xml, */*
-> Content-Type: application/x-www-form-urlencoded
-> Content-Length: 215
-> 
>> client_id=<REDACTED>&grant_type=authorization_code&client_secret=<REDACTED>&code=M27d6c2f3-5d18-26e8-7a26-d7529e94c42d&redirect_uri=http%3A%2F%2Flocalhost%3A8080
```

Unfortunately, at this point I ran into the embedded nul error we [discussed](https://github.com/Azure/AzureAuth/issues/16) yesterday.

```
Warning: Error in rawToChar: embedded nul in string: '\023 . . .
```

**Comment by Hong-Revo** [comment] 2019-10-15 19:06
I can't repro that error.

Put this call in your UI exactly as shown:

```r
auth_uri <- build_authorization_uri(resource, tenant, app, redirect_uri=redirect, version=2)
```

And put this in your server exactly as shown:

```r
token <- get_azure_token(resource, tenant, app, password=password,
                         auth_type="authorization_code",
                         authorize_args=list(redirect_uri=redirect),
                         auth_code=code, version=2, use_cache=FALSE)
```

**Comment by nteetor** [comment] 2019-10-15 19:46
I reduced the problem to a smaller shiny application. I still get the same embedded nul error. I couldn't use the snippets _exactly_ as you provided because the config file refers to the values in capcase. However, I made no changes to unnamed arguments or named arguments or spacing.

```R
library(shiny)
library(AzureAuth)

azure <- config::get("azure")

options(
  shiny.port = as.numeric(httr::parse_url(azure$REDIRECT)$port)
)

shinyApp(
  ui = function(req) {
    qs <- parseQueryString(req$QUERY_STRING)
    redirect <- NULL
    
    if (is.null(qs$code)) {
      # Auth URI created here
      auth_uri <- with(azure, {
        build_authorization_uri(RESOURCE, TENANT, APP, redirect_uri=REDIRECT, version=2)
      })
      
      redirect <- tags$script(HTML(paste0("window.location.replace(\"", auth_uri, "\");")))
    }
    
    fluidPage(
      tags$head(
        redirect
      ),
      tags$p("Hello, world.")
    )
  },
  server = function(input, output, session) {
    qs <- isolate(parseQueryString(session$clientData$url_search))
    
    if (!is.null(qs$code)) {
      code <- qs$code
      
      # Get token
      token <- with(azure, {
        get_azure_token(RESOURCE, TENANT, APP, password=SECRET,
                        auth_type="authorization_code",
                        authorize_args=list(redirect_uri=REDIRECT),
                        auth_code=code, version=2, use_cache=FALSE)
      })
    }
  }
)
```

**Comment by nteetor** [comment] 2019-10-15 19:47
I working to get my hands on a Windows machine to see the problem persists there, too.

**Comment by Hong-Revo** [comment] 2019-10-15 20:00
Your code works fine for me; I even registered a new app with redirect URI localhost:8080. Check that you haven't misconfigured your app registration in AAD, or try registering a fresh app.

The embedded nul error has nothing to do with your machine, it's because the endpoint is sending back an invalid access token.

**Comment by nteetor** [comment] 2019-10-15 20:14
This is a little more terrifying. I'm sure at all what could be misconfigured. I touched about 5 settings, so I'll review those changes. I also realize this is definitely outside the scope of your work. 

Regarding checking for `NULL`, that's what the if statement is there for,  :)

```R
if (!is.null(qs$code)) {  # <- copied from above
      code <- qs$code
      
      # Get token
      token <- with(azure, {
        get_azure_token(RESOURCE, TENANT, APP, password=SECRET,
                        auth_type="authorization_code",
                        authorize_args=list(redirect_uri=REDIRECT),
                        auth_code=code, version=2, use_cache=FALSE)
      })
```

**Comment by Hong-Revo** [comment] 2019-10-15 20:26
Re: app registration, you shouldn't need to touch anything, really. The only things you need to set are the redirect URI, plus a client secret. Everything else can be left as-is.

From my test app's page:

![image](https://user-images.githubusercontent.com/11328890/66866931-082a0980-efe6-11e9-992e-291562c9fdc6.png)
![image](https://user-images.githubusercontent.com/11328890/66866961-1710bc00-efe6-11e9-858e-88fa9037c74e.png)
![image](https://user-images.githubusercontent.com/11328890/66866998-255ed800-efe6-11e9-9ae8-d0eeb048e1ec.png)
![image](https://user-images.githubusercontent.com/11328890/66867016-2c85e600-efe6-11e9-87de-46f52d1e55df.png)

**Comment by nteetor** [comment] 2019-10-15 20:39
Thank you for the screenshots! I adjusted my settings, I had a couple extra API permissions. I still run into the nul error. 

So, at this point I am burning down the old app and registering a new one to be safe.

**Comment by nteetor** [comment] 2019-10-15 20:44
Would you mind sending the value you passed as `resource` to `get_azure_token()`?

**Comment by Hong-Revo** [comment] 2019-10-15 21:01
RESOURCE <- c("https://graph.microsoft.com/.default", "openid", "profile", "email", "offline_access")

**Comment by nteetor** [comment] 2019-10-15 21:32
Shoot, that's what I have to. The new application didn't help unfortunately. I think at this point you've helped far beyond expectations. I'll have to poke around docs and help pages for a while.

**Comment by Hong-Revo** [comment] 2019-10-15 23:51
I did actually see that embedded nul error once, but haven't been able to reproduce it. I'm closing this issue since there doesn't appear to be anything wrong with AzureAuth. If you're still unable to get it working, send me an email.

**Closed by Hong-Revo** 2019-10-15 23:51 UTC

**Comment by hongooi73** [comment] 2021-03-24 15:30
This is rather old, but still: I've learned what's causing the error above. If you authenticate to Azure with a **personal** Microsoft account, the resulting access token is not a regular JWT, but a custom format that is Microsoft-only. Because of this, trying to read its contents will fail -- you have to treat it as an opaque blob, basically.

This should only happen with a personal account. If you authenticate with a work & school account (ie, the one you use when you login to an organisation), everything should behave normally.

**Comment by erdemakkas** [comment] 2021-05-10 11:17
> 
> 
> Hello again,
> 
> I am not sure whether to open an issue here or under the AzureGraph repo. I am struggling to understand how to access basic user information like their username or email as part of the auth token payload. The Azure AD documentation suggests their email or username can come back with the payload. I've tried adjusting my application's settings and api permissions and have never once seen any additional info come back.
> 
> I thought perhaps I needed to use graph then. However, I first ran into this error when trying to use my auth token to call `create_graph_login()`,
> 
> ```
> Current authenticated context is not valid for this
> request. This occurs when a request is made to an
> endpoint that requires user sign-in. For example, /me
> requires a signed-in user.  Acquire a token on behalf
> of a user to make requests to these endpoints.  Use
> the OAuth 2.0 authorization code flow for mobile and
> native apps and the OAuth 2.0 implicit flow for
> single-page web apps.
> ```
> 
> So, I followed the AzureAuth example for acquiring a token on behalf of another token. I noticed the example uses two distinct app IDs. I am working with a single application, one id. Here is the error I got back while trying to request a second token for graph on behalf of my initial auth token,
> 
> ```
> Assertion failed signature validation. [Reason - The provided signature value did not match the expected signature value., Thumbprint of key used by client: '<REDACTED ALPHA NUMERIC>', Found key 'Start=08/25/2019 00:00:00, End=08/24/2024 00:00:00']
> ```
> 
> My application does request the resource in the auth process,
> 
> ```
> https://graph.microsoft.com/.default
> ```
> 
> And I think I have the correct permissions set,
> 
> <img alt="image" width="529" src="https://user-images.githubusercontent.com/3228369/66837796-97291a00-ef31-11e9-9758-d783d353962c.png">
> 
> Do you see any glaring issues in my worflow? Can I avoid using AzureGraph and still get username and email address (if set) with my initial auth token request? Thank you again.

@nteetor I had similar issue of getting user information in #44 . Were you able to get any user info in the Shiny app?
